#define TAREA_MOTOR "Alinear la salida del motor"
#define TAREA_DISTRIBUIDOR "Calibrar distribuidor"
#define TAREA_DATOS "Descargar datos"
#define TAREA_ENERGIA "Desviar energia"
#define TAREA_ESCUDOS "Encender escudos"
#define TAREA_DIRECCION "Estabilizar direccion"
#define TAREA_FILTRO "Limpiar el filtro O2"
#define TAREA_MAPA "Mapa de navegacion"

#define SALA_MOTORES "Motores"
#define SALA_ELECTRICIDAD "Electricidad"
#define SALA_CAFETERIA "Cafeteria"
#define SALA_COMUNICACIONES "Comunicaciones"
#define SALA_ARMERIA "Armeria"
#define SALA_NAVEGACION "Navegacion"
#define SALA_O2 "O2"
#define SALA_SEGURIDAD "Seguridad"
#define SALA_ESCUDOS "Escudos"